---
name: load_balancing_for_pipeline_notification_worker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66459
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/336517
milestone: '14.2'
type: development
group: group::pipeline authoring
default_enabled: false

